TRUNCATE TABLE configuration CASCADE;

INSERT INTO configuration (key, value)
VALUES ('JWT_SECRET', 'local test')
ON CONFLICT DO NOTHING;

INSERT INTO configuration (key, value)
VALUES ('JWT_EXPIRATION', '5555')
ON CONFLICT DO NOTHING;

INSERT INTO configuration (key, value)
VALUES ('RESET_PASSWORD_EXPIRATION', '5555')
ON CONFLICT DO NOTHING;

INSERT INTO configuration (key, value)
VALUES ('CREATE_PASSWORD_EXPIRATION', '5555')
ON CONFLICT DO NOTHING;
